### ISSUE TITLE
error with ref_batch due to incorrect slicing

### ISSUE THREAD

**Issue by alexandradanyi** [epigenelabs/inmoose#14]
https://github.com/epigenelabs/inmoose/blob/7f1915169dc8667bf7763ad54b590fbc3aedc4b6/inmoose/pycombat/pycombat_norm.py#L458

Hi,

I've got an error when I tried to use the 'ref_batch' argument of 'pycombat_norm()'. Eventually I figured that the slicing of the 2D arrays was incorrect. The following line automatically tries to slice the array on axis=0 (rows), which is the gene expression information/genes and not the samples in axis=1 (columns):
`bayes_data[batches[ref]] = dat[batches[ref]]`

It would be very easy to fix this:
`bayes_data[:, batches[ref]] = dat[:, batches[ref]]`

I wanted to make a pull request so I've made a local branch with the change but I cannot commit it to the remote because I don't have permission.

Could you check if I'm right and if so, fix this issue (since I don't have permission to commit)? Based on the documentation, the input data matrix described in https://github.com/epigenelabs/inmoose#batch-effect-correction should follow the gene expression = rows and samples = columns format. In this case, the slicing of bayes_data and dat matrices should be fixed accordingly as I described.

Kind regards,
Alex

**Comment by EpigeneMax** [comment]
Dear Alexandra,

Thank you for reporting this, and sorry for the late reply.

I was not able to reproduce the issue you describe. It may have been fixed by the code evolutions we made since the issue was opened. I suggest you retry with the latest version (`pip install -U inmoose` to upgrade your version of `inmoose`). 
If not, could you please provide a minimal working example to reproduce it, and the version of `inmoose` on which you observe the issue?

**Comment by CalvinRusley** [comment]
Can confirm this is still a problem in 0.8.1. When line 458 is called, the dimensions of bayes_data are (expression,samples) and the dat[batches[ref]] call should be slicing a set of samples in dimension 1, not dimension 0.

**Comment by josh-gree** [comment]
Reproduction of the error can be found here -> https://gist.github.com/josh-gree/c37df6d4bee340729474c72694b9b447

**Comment by EpigeneMax** [comment]
fixed by #156
